# Generated by Django 4.2.13 on 2024-06-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='patient',
        ),
    ]
