# Generated by Django 4.2.13 on 2024-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_treatmentplan_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='spending',
            field=models.FloatField(default=0),
        ),
    ]
