# Generated by Django 4.2.13 on 2024-06-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_treatmentplan_spending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='date',
        ),
    ]
