# Generated by Django 4.2.13 on 2024-06-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_treatmentplan_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentplan',
            old_name='treatment',
            new_name='description',
        ),
    ]
