# Generated by Django 4.2.13 on 2024-08-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_polls_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='spending',
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='antibiotic_names',
            field=models.CharField(default='', help_text='Comma-separated list of antibiotics used in the treatment', max_length=255),
        ),
    ]
